# Generated by Django 6.0.3 on 2026-04-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherrecord',
            name='raw_response',
        ),
    ]
